const qs=(s,el=document)=>el.querySelector(s);const qsa=(s,el=document)=>[...el.querySelectorAll(s)];const root=document.documentElement;
const elHome=qs('#home'),elAppView=qs('#app-view'),elAppTitle=qs('#app-title'),elAppContent=qs('#app-content'),elBtnHome=qs('#btn-home'),elBtnBack=qs('#btn-back'),elHelp=qs('#btn-help'),elHelpModal=qs('#help-modal'),elHelpClose=qs('#help-close'),elTheme=qs('#btn-theme'),elStatusPill=qs('#status-pill');
function setStatusTime(){const t=new Date();const hh=t.getHours();const mm=String(t.getMinutes()).padStart(2,'0');qs('#status-time').textContent=`${((hh+11)%12+1)}:${mm}`;}
document.addEventListener('DOMContentLoaded',()=>{const v=document.getElementById('app-view');if(v)v.setAttribute('hidden','');setStatusTime();});setInterval(setStatusTime,3e4);
const APPS={timeline:{title:'iPhone Timeline',prosSections:[{type:'kpis',items:[{label:'Launch',value:'2007'},{label:'Models',value:'40+'},{label:'Active Users',value:'~1.5B'}]},{type:'text',heading:'Pros Timeline',body:'App Store, Retina, Touch/Face ID, 5G, ecosystem interoperability.'},{type:'figure',label:'(Pros) Add your timeline graphic here.'}],consSections:[{type:'kpis',items:[{label:'Downsides',value:'trade-offs'}]},{type:'text',heading:'Cons Timeline',body:'Lock-in, rising costs, attention load, e-waste concerns.'},{type:'figure',label:'(Cons) Add your timeline graphic here.'}]},design:{title:'Design & UX',prosSections:[{type:'text',heading:'Pros',body:'Clarity, consistency, accessibility, haptics, performance.'}],consSections:[{type:'text',heading:'Cons',body:'Closed system, customization limits, repairability.'}]},comms:{title:'Communication & Social',prosSections:[{type:'text',heading:'Pros',body:'Global reach, creative expression, safety/alerts.'}],consSections:[{type:'text',heading:'Cons',body:'FOMO, distraction, social comparison.'}]},work:{title:'Work',prosSections:[{type:'text',heading:'Pros',body:'Mobility, productivity on-the-go, accessibility tools.'}],consSections:[{type:'text',heading:'Cons',body:'Always-on expectations, boundary erosion.'}]},economy:{title:'Economy',prosSections:[{type:'text',heading:'Pros',body:'New markets, developer ecosystem, payments.'}],consSections:[{type:'text',heading:'Cons',body:'Platform fees, lock-in, monopolistic dynamics.'}]},culture:{title:'Culture',prosSections:[{type:'text',heading:'Pros',body:'Democratized creation, civic coordination.'}],consSections:[{type:'text',heading:'Cons',body:'Virality over depth, aesthetic pressures.'}]},health:{title:'Health',prosSections:[{type:'text',heading:'Pros',body:'Health tracking, accessibility, mindfulness tooling.'}],consSections:[{type:'text',heading:'Cons',body:'Sleep disruption, anxiety, attention fragmentation.'}]},sources:{title:'Sources',prosSections:[{type:'text',heading:'Works Cited',body:'Place MLA sources here.'}],consSections:[{type:'text',heading:'Works Cited',body:'Place MLA sources here.'}]}};
const navStack=[];function isLight(){return root.classList.contains('light');}function currentSections(app){return isLight()?(app.prosSections||[]):(app.consSections||[]);}
function renderSection(s){const wrap=document.createElement('section');wrap.className='card';if(s.type==='kpis'){const g=document.createElement('div');g.className='kpis';(s.items||[]).forEach(it=>{const k=document.createElement('div');k.className='kpi';k.innerHTML=`<div class="label">${it.label}</div><div class="value">${it.value}</div>`;g.appendChild(k);});wrap.appendChild(g);}else if(s.type==='text'){if(s.heading){const h=document.createElement('h3');h.textContent=s.heading;wrap.appendChild(h);}const p=document.createElement('p');p.innerHTML=s.body||'';wrap.appendChild(p);}else if(s.type==='figure'){const f=document.createElement('div');f.className='figure';f.textContent=s.label||'Figure';wrap.appendChild(f);}return wrap;}
function openApp(key){const app=APPS[key];if(!app)return;elAppTitle.textContent=app.title;elAppContent.innerHTML='';currentSections(app).forEach(sec=>elAppContent.appendChild(renderSection(sec)));navStack.length=0;navStack.push(key);elAppView.hidden=false;elHome.style.opacity='0';elHome.style.pointerEvents='none';}
function refreshOpenAppIfAny(){if(navStack.length===0)return;const key=navStack[navStack.length-1];const app=APPS[key];if(!app)return;elAppTitle.textContent=app.title;elAppContent.innerHTML='';currentSections(app).forEach(sec=>elAppContent.appendChild(renderSection(sec)));}
function goHome(){if(!elAppView.hasAttribute('hidden')){elAppView.setAttribute('hidden','');}elHome.style.opacity='1';elHome.style.pointerEvents='auto';}
function goBack(){goHome();}
qsa('.app-icon').forEach(btn=>btn.addEventListener('click',()=>openApp(btn.dataset.app)));
elBtnHome.addEventListener('click',goHome);elBtnBack.addEventListener('click',goBack);
elHelp.addEventListener('click',()=>elHelpModal.showModal());elHelpClose.addEventListener('click',()=>elHelpModal.close());
function applyModeIndicators(){const text=isLight()?'Pros':'Cons';elStatusPill.textContent=text;}
elTheme.addEventListener('click',()=>{const light=root.classList.toggle('light');localStorage.setItem('theme',light?'light':'dark');applyModeIndicators();refreshOpenAppIfAny();});
if(localStorage.getItem('theme')==='light'){root.classList.add('light');}
applyModeIndicators();
window.LegacyMap={open:openApp,home:goHome,config:APPS};
